[profile.default]
retries = 0                                            # this is the default, so it doesn't need to be specified
slow-timeout = { period = "15s", terminate-after = 4 }


[profile.ci]
retries = 1
slow-timeout = { period = "15s", terminate-after = 2 }
