sequenceDiagram
    actor C as Client
    Box Server
    participant Listener
    participant Stream as ClientStream
    participant CL as ClusterActor
    participant CA as CacheActor
    
    end
    
    loop wait for connection
        activate Listener
        C ->> Listener: Connect
        Listener --) Stream : Create
        deactivate Listener
    end

    loop 
        Stream --)+ Stream: wait & receive request
        alt Write Request
            Stream -->> CL: route request
            activate CL
            CL -->> CL : Register callback, wait for concensus
            CL -->> CL : Consensus reached
            deactivate CL
            CL -->> CA : route request
            CA -->> CL: return response
            CL -->> Stream: return response
        else  Read Request
        Stream -->> CA: route request
        CA -->> Stream: return response
        Stream -->> C: return response
        end
    end

    
    