
---
title : Clustering
---

sequenceDiagram
    participant s as MasterServer
    
    
    actor Cache
    actor Config
    actor Cluster
    actor peer_listener
    
    actor client_listener
    participant SlaveServer
    actor slave_peer_listener
    participant SlaveServer2

    par 
        s-->>Cache: spawn
    and 
        s-->>Config: spawn
    and 
        s-->>Cluster: spawn
        Cluster --> Cluster : send heartbeat
        Note right of Cluster : Cluster periodically sends heartbeat to peers 
    and
        s -->>client_listener:spawn
        
    and 
        SlaveServer -->> slave_peer_listener: spawn 
        Note right of SlaveServer : SlaveServer also listens for incoming peer connections
    and 
    

        
        s-->>peer_listener: spawn
        
        loop 
            SlaveServer -->>+ peer_listener: bind 
            peer_listener -->- SlaveServer: threeway handshake
            peer_listener -->> SlaveServer : disseminate peer infomation            

            par 
                peer_listener -->>+ Cluster : pass stream
                Cluster -->>- Cluster : add peer
        
            and
                SlaveServer --> SlaveServer :try connect to other peers  
            end
            
        end

        SlaveServer2 -->>+ peer_listener: bind 
        peer_listener -->- SlaveServer2: threeway handshake
        peer_listener -->> SlaveServer2 : disseminate peer infomation  
        peer_listener -->>+ Cluster : pass stream
        SlaveServer2 -->+ slave_peer_listener : bind
        slave_peer_listener -->- SlaveServer2: threeway-handshake
        
  
    end

    
    

 
    