
---
title : Clustering
---

sequenceDiagram
    participant s as Leader    
    actor Cache
    actor Config
    actor Cluster
    actor peer_listener
    
    actor client_listener
    participant Follower
    actor follower_listener
    participant Follower2

    par 
        s-->>Cache: spawn
    and 
        s-->>Config: spawn
    and 
        s-->>Cluster: spawn
        Cluster --> Cluster : send heartbeat
        Note right of Cluster : Cluster periodically sends heartbeat to peers 
    and
        s -->>client_listener:spawn
        
    and 
        Follower -->> follower_listener: spawn 
        Note right of Follower : Follower also listens for incoming peer connections
    and 
        
        s-->>peer_listener: spawn
        
        loop 
            Follower -->>+ peer_listener: bind 
            peer_listener -->- Follower: threeway handshake
            peer_listener -->> Follower : disseminate peer infomation            

            par 
                peer_listener -->>+ Cluster : pass stream
                Cluster -->>- Cluster : add peer
        
            and
                Follower --> Follower :try connect to other peers  
            end
            
        end

        Follower2 -->>+ peer_listener: bind 
        peer_listener -->- Follower2: threeway handshake
        peer_listener -->> Follower2 : disseminate peer infomation  
        peer_listener -->>+ Cluster : pass stream
        Follower2 -->+ follower_listener : bind
        follower_listener -->- Follower2: threeway-handshake
        
  
    end

    
    

 
    