---
title: Follower reads(RYOW)
---
sequenceDiagram
    actor C as Client
    participant L as Leader
    participant F as Follower

    note over L,F : X:1<br>consensus_index:1

    C->>L: write(X,5)
    note over L : X:5<br>consensus_index:2
    note over F : X:1<br>consensus_index:1
    L->>C: consensus_index:2
    C->>F: read(X,consensus_index=2)
    F--)F: wait for latest consensus_index
    L->>F: write(X,5,consensus_index=2)
    note over F : X:5<br>consensus_index:2
    F->>C: X:5

    