---
title: Full Sync Scenario
---
sequenceDiagram
    participant L as Leader
    participant F as Follower
    L ->> L: append entry * 5
    L ->> L: Snapshot (until commit_idx 5)
    F ->> L: Connect (replid:?, commit_idx:0)
    L ->> F: Send Full Sync (Snapshot with commit_idx 5)