---
title: Full Sync Scenario
---
sequenceDiagram
    participant L as Leader
    participant F as Follower
    L ->> L: append entry * 5
    L ->> L: Snapshot (until hwm 5)
    F ->> L: Connect (replid:?, hwm:0)
    L ->> F: Send Full Sync (Snapshot with hwm 5)